class ImageAsset {
  static String basePath = 'assets/images/';

  static String home = '${basePath}home.png',
      news = '${basePath}news.png',
      events = '${basePath}events.png',
      explore = '${basePath}explore.png',
      arrow = '${basePath}arrow.png',
      searcher = '${basePath}search.png',
      filters = '${basePath}filtry.png',
      benefist = '${basePath}benefist.jpeg',
      love = '${basePath}love.jpeg',
      spodek = '${basePath}spodek.jpeg',
      bober = '${basePath}bober.jpeg',
      culture = '${basePath}kultura.png',
      translation = '${basePath}tłumaczenie.jpeg',
      films = '${basePath}filmowa.jpeg',
      spodekSnipped = '${basePath}spodek_snipped.png',
      boberSnipped = '${basePath}bober_snipped.png',
      cultureSnipped = '${basePath}kultura_snipped.png',
      translationSnipped = '${basePath}tlumaczenie_snipped.png',
      filmsSnipped = '${basePath}filmowa_snipped.png',
      fav = '${basePath}fav.png',
      filledFav = '${basePath}filled_fav.png',
      smallArrow = '${basePath}small_arrow.png',
      smallArrowFav = '${basePath}small_arrow_fav.png',
      calendar = '${basePath}calendar.png',
      share = '${basePath}share.png',
      map = '${basePath}map.png',
      page = '${basePath}page.png',
      free = '${basePath}bezplatne.png',
      paid = '${basePath}platne.png',
      facebook = '${basePath}fb.png',
      instagram = '${basePath}ig.png',
      cancel = '${basePath}cancel.png',
      expand = '${basePath}expand.png';
}
